---
- name: install_mongodb playbook
  hosts: all
  become: yes
  tasks:
    - name: wget -qO - https://www.mongodb.org/static/pgp/server-4.2.asc | sudo apt-key add -
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.2.asc

    - name: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.2.list
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
        filename: mongodb-org-4.2

    - name: apt update -y && apt install -y mongodb-org
      apt:
        name: mongodb-org
        update_cache: yes

    - name: systemctl enable mongod && systemctl start mongod
      service:
        name: mongod
        enabled: yes
        state: started
