---
- name: Sleeping
  pause:
    minutes: 1
  changed_when: False
  tags: ruby
- name: Install ruby and rubygems and required packages
  apt: "name={{ item }} state=present"
  with_items:
    - ruby-full
    - ruby-bundler
    - build-essential
  tags: ruby
